# Generated by Django 4.1.1 on 2023-01-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-id"],
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
            },
        ),
    ]
