# Generated by Django 4.1.1 on 2023-06-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                db_index=True,
                default="Unread",
                max_length=6,
            ),
        ),
    ]
