# Generated by Django 4.1.1 on 2023-01-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_eventreview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventreview",
            options={
                "ordering": ["-id"],
                "verbose_name": "event review",
                "verbose_name_plural": "event reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-id"],
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
            },
        ),
    ]
