version: "3.8"

services: 
  db:
    container_name: db
    env_file:
      - stack.env
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: pg_isready -U postgres -d postgres
      timeout: 5s
      retries: 20
      
  api:
    container_name: api
    env_file:
      - stack.env
    image: registry.it-flumx.com/flumx_te_blanball_be_test:latest
    command: bash compose/local/django-start.sh
    ports:
      - 49200:8000
    volumes:
      - api-data:/usr/src/blanball
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network    
    links:
     - redis
  nginx:
    container_name: nginx
    env_file:
      - stack.env
    image: nginx:latest
    ports:
      - 49281:81
    volumes:
      - api-data:/usr/src/blanball
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  redis:
    container_name: redis
    env_file:
      - stack.env
    image: redis:latest
    volumes:
      - redis-data:/usr/src/blanball/storage/redis/data
    networks:
      - app-network  
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 3s
      retries: 5

  celery-worker:
    env_file:
      - stack.env
    container_name: celery-worker
    image: registry.it-flumx.com/flumx_te_blanball_be_test:latest
    restart: always
    command: bash compose/local/celery-worker-start.sh
    networks:
      - app-network  
    depends_on:
      redis:
        condition: service_healthy

  celery-beat:
    container_name: celery-beat
    env_file:
      - stack.env
    image: registry.it-flumx.com/flumx_te_blanball_be_test:latest
    restart: always 
    command: bash compose/local/celery-beat-start.sh
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin
    env_file:
      - stack.env
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/usr/src/blanball/storage/pgadmin/data
    networks:
      - app-network
    ports:
      - 49280:80

  db_backup:
    container_name: db_backup
    env_file:
      - stack.env
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - db-backup-data:/usr/src/blanball/storage/db-backup/data
    networks:
      - app-network
    depends_on:
      db:
        condition: service_started
  ftp-server:
    env_file:
      - stack.env
    container_name: ftp-server
    image: garethflowers/ftp-server
    ports:
      - '49221:21/tcp'
    volumes:
      - ftp-server-data:/home/user
    networks:
      - app-network
    
networks:
  app-network:
     driver: bridge    
     
volumes:
  redis-data:
  pgadmin-data:
  db-backup-data:
  ftp-server-data:
  api-data:

