version: "3.8"

services: 
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - stack.env
    volumes:
      - db-data:/usr/src/blanball/storage/db/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      timeout: 40s
      retries: 20
    networks:
      - app-network
      
  api:
    container_name: api
    env_file:
      - stack.env
    build: 
      context: .
      dockerfile: compose/Dockerfile
    command: bash ./compose/local/django-start.sh
    volumes:
      - .:/usr/src/blanball
    ports:
      - "49200:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network    
    links:
     - redis
     
  redis:
    container_name: redis
    env_file:
      - stack.env
    image: redis:latest
    volumes:
      - redis-data:/usr/src/blanball/storage/redis/data
    networks:
      - app-network  
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 3s
      retries: 5

  celery-worker:
    env_file:
      - stack.env
    container_name: celery-worker
    build: 
      context: .
      dockerfile: compose/Dockerfile
    restart: always
    command: bash compose/local/celery-worker-start.sh
    volumes:
      - celery-worker-data:/usr/src/blanball/storage/celery-worker/data
    networks:
      - app-network  
    depends_on:
      redis:
        condition: service_healthy

  celery-beat:
    env_file:
      - stack.env
    container_name: celery-beat
    build: 
      context: .
      dockerfile: compose/Dockerfile
    restart: always 
    command: bash compose/local/celery-beat-start.sh
    volumes:
      - celery-beat-data:/usr/src/blanball/storage/celery-beat/data
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    
networks:
  app-network:
     driver: bridge    
     
volumes:
  db-data:
  redis-data:
  celery-worker-data:     
  celery-beat-data: 
