version: '3.8'

x-api-common: &api-common
    image: registry.it-flumx.com/flumx_blanball_be_prod:latest

    env_file:
        - stack.env
    entrypoint: scripts/entrypoint.sh

    depends_on:
        db-prod:
            condition: service_healthy
        redis-prod:
            condition: service_healthy
    networks:
        - app-network-prod
    links:
        - redis-prod

services:
    proxy-prod:
        container_name: proxy-prod
        env_file:
            - stack.env
        image: registry.it-flumx.com/blanball-proxy-prod:latest
        ports:
            - 49298:80
        networks:
            - app-network-prod
        depends_on:
            api-prod:
                condition: service_started

    api-prod:
        <<: *api-common
        container_name: api-prod
        command: api-deploy
        user: deploy
        labels:
          - "traefik.enable=true"
          ## HTTP
          - "traefik.http.routers.api-prod-web.entrypoints=web"
          - "traefik.http.routers.api-prod-web.rule=Host(`api.blanball.com`) && PathPrefix(`/api`)"
          - "traefik.http.services.api-prod.loadbalancer.server.port=8000"
          ## Redirect  
          - "traefik.http.middlewares.api-prod-redirect-web-secure.redirectscheme.scheme=https"
          - "traefik.http.routers.api-prod-web.middlewares=api-prod-redirect-web-secure"
          ## HTTPS
          - "traefik.http.routers.api-prod-web-secure.entrypoints=web-secure"
          - "traefik.http.routers.api-prod-secure.rule=Host(`api-prod.blanball.com`) && PathPrefix(`/api`)"
          - "traefik.http.routers.api-prod-web-secure.tls=true"
          - "traefik.http.routers.api-prod-web-secure.tls.certResolver=sample"
        
    daphne-prod:
        <<: *api-common
        container_name: daphne-prod
        command: daphne
        user: deploy
        labels:
          - "traefik.enable=true"
          ## HTTP
          - "traefik.http.routers.daphne-prod-web.entrypoints=web"
          - "traefik.http.routers.daphne-prod-web.rule=Host(`api.blanball.com`) && PathPrefix(`/ws`)"
          - "traefik.http.services.daphne-prod.loadbalancer.server.port=10000"
          ## Redirect  
          - "traefik.http.middlewares.daphne-prod-redirect-web-secure.redirectscheme.scheme=https"
          - "traefik.http.routers.daphne-prod-web.middlewares=daphne-prod-redirect-web-secure"
          ## HTTPS
          - "traefik.http.routers.daphne-prod-web-secure.entrypoints=web-secure"
          - "traefik.http.routers.daphne-prod-secure.rule=Host(`api.blanball.com`) && PathPrefix(`/ws`)"
          - "traefik.http.routers.daphne-prod-web-secure.tls=true"
          - "traefik.http.routers.daphne-prod-web-secure.tls.certResolver=sample"
        
    celery-worker-prod:
        <<: *api-common
        container_name: celery-worker-prod
        user: deploy
        command: celery-worker

    celery-beat-prod:
        <<: *api-common
        container_name: celery-beat-prod
        command: celery-beat

    db-prod:
        container_name: db-prod
        env_file:
            - stack.env
        image: postgis/postgis:latest
        restart: always
        volumes:
            - db-data-prod:/var/lib/postgresql/data
        networks:
            - app-network-prod
        healthcheck:
            test: pg_isready -U postgres -d postgres
            timeout: 5s
            retries: 20

    redis-prod:
        container_name: redis-prod
        env_file:
            - stack.env
        image: redis:latest
        restart: always
        volumes:
            - redis-data-prod:/usr/src/blanball/storage/redis-prod/data
        networks:
            - app-network-prod
        healthcheck:
            test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
            timeout: 3s
            retries: 5

    pgadmin-prod:
        container_name: pgadmin-prod
        env_file:
            - stack.env
        image: dpage/pgadmin4:latest
        restart: always
        volumes:
            - pgadmin-data-prod:/usr/src/blanball/storage/pgadmin-prod/data
        networks:
            - app-network-prod
        ports:
            - 49283:${PGADMIN_LISTEN_PORT}

    db_backup-prod:
        container_name: db_backup-prod
        env_file:
            - stack.env
        image: prodrigestivill/postgres-backup-local
        restart: always
        volumes:
            - db-backup-data-prod:/usr/src/blanball/storage/db-backup-prod/data
        networks:
            - app-network-prod
        depends_on:
            db-prod:
                condition: service_started

    minio-prod:
        container_name: minio-prod
        env_file:
            - stack.env
        image: minio/minio
        volumes:
            - minio-data-prod:/minio-data-prod
        command: 'minio server /minio-data-prod --console-address ":9001"'
        ports:
            - 49293:9000
            - 49294:9001
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 30s
            timeout: 20s
            retries: 3
        networks:
            - app-network-prod

networks:
    app-network-prod:
        driver: bridge

volumes:
    redis-data-prod:
    pgadmin-data-prod:
    db-backup-data-prod:
    minio-data-prod:
    db-data-prod:
