version: "3.8"

services: 

  proxy:
    container_name: proxy
    env_file: 
      - stack.env
    image: registry.it-flumx.com/blanball-proxy:latest
    restart: always
    ports:
      - 49299:80
    networks:
      - app-network
    depends_on:
      api:
        condition: service_started
      
  api:
    container_name: api
    env_file: 
      - stack.env
    image: registry.it-flumx.com/flumx_te_blanball_be_test:latest
    user: deploy
    entrypoint: compose/entrypoint.sh
    restart: always
    command: api-deploy
    ports:
      - 49200:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network    
    links:
     - redis

  static:
    container_name: static
    env_file: 
      - stack.env
    image: registry.it-flumx.com/flumx_te_blanball_be_test_static:latest
    restart: always
    networks:
      - app-network
    depends_on:
      api:
        condition: service_started

  daphne:
    container_name: daphne
    env_file: 
      - stack.env
    image: registry.it-flumx.com/flumx_te_blanball_be_test:latest
    user: deploy
    restart: always
    entrypoint: compose/entrypoint.sh
    command: daphne
    ports:
      - 49290:9000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network    
    links:
     - redis

  db:
    container_name: db
    env_file: 
      - stack.env
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: pg_isready -U postgres -d postgres
      timeout: 5s
      retries: 20

  redis:
    container_name: redis
    env_file: 
      - stack.env
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/usr/src/blanball/storage/redis/data
    networks:
      - app-network  
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 3s
      retries: 5

  celery-worker:
    env_file: 
      - stack.env
    container_name: celery-worker
    image: registry.it-flumx.com/flumx_te_blanball_be_test:latest
    user: deploy
    restart: always
    entrypoint: compose/entrypoint.sh
    command: celery-worker
    networks:
      - app-network  
    depends_on:
      redis:
        condition: service_healthy

networks:
  app-network:
    driver: bridge    
     
volumes:
  redis-data:
  pgadmin-data:
  db-backup-data:
  ftp-server-data:
