version: "3.8"

services: 
  db:
    container_name: db
    ports:
      - 5432:5432
    image: postgres:latest
    volumes:
      - ./storage/db/data:/usr/src/blanball/storage/db/data
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=root
       - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      timeout: 40s
      retries: 20    
  api:
    container_name: api
    build: .
    command: bash django-start.sh
    volumes:
      - ./storage/api/data:/usr/src/blanball/storage/api/data
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
     - redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis/data:/usr/src/blanball/storage/redis/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 3s
      retries: 5

  celery-worker:
    container_name: celery-worker
    build: .
    command: bash celery-worker-start.sh
    volumes:
      - ./storage/celery-worker/data:/usr/src/blanball/storage/celery-worker/data
    depends_on:
      redis:
        condition: service_healthy

  celery-beat:
    container_name: celery-beat
    build: .
    command: bash celery-beat-start.sh
    volumes:
      - ./storage/beat/data:/usr/src/blanball/storage/celery-beat/data
    depends_on:
      redis:
        condition: service_healthy

volumes:
  db:
    driver: local
  redis:
    driver: local




    