version: "3.7"

services: 
  web:
    container_name: web
    build: .
    command: bash start.sh
    volumes:
      - .:/usr/src/blanball
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db
  db:
    ports:
      - 3306:3306
    container_name: db
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'blanball'
      MYSQL_PASSWORD: 'Djoncarton1921_'
      MYSQL_ROOT_HOST: '%'  
      MYSQL_ROOT_PASSWORD: 'Djoncarton1921_'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10