version: "3.8"

services: 
  db:
    container_name: db
    ports:
      - 5432:5432
    image: postgres:latest
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=root
       - POSTGRES_DB=postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      timeout: 40s
      retries: 20
  api:
    container_name: api
    build: .
    command: bash django-start.sh
    volumes:
      - .:/usr/src/blanball
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 3s
      retries: 5

  celery:
    container_name: celery
    build: .
    command: >
      bash -c "cd project && 
              celery -A project worker -l info"
    volumes:
      - .:/usr/src/blanball
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db:
    driver: local
  redis:
    driver: local





    