
version: "3.3"

services: 
  web:
    build: .
    command: python /usr/src/blanball/project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/blanball
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db
  db:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'blanball'
      MYSQL_PASSWORD: 'Djoncarton1921_' 
      MYSQL_ROOT_PASSWORD: 'Djoncarton1921_'