version: "3.8"

services:
  db:
    container_name: db
    env_file: 
      - .env
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports: 
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -d postgres
      timeout: 5s
      retries: 20

  api:
    container_name: api
    env_file: 
      - .env
    entrypoint: scripts/entrypoint.sh
    command: api
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/src/blanball
    networks:
      - app-network
    ports: 
      - 8000:8000
    depends_on:
      db: 
        condition: service_healthy
      redis: 
        condition: service_healthy
    links: 
      - redis

  redis:
    container_name: redis
    env_file: 
      - .env
    image: redis:7.0.4-alpine
    volumes: 
      - redis-data:/usr/src/blanball/storage/redis/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 5s
      retries: 20

  celery-worker: 
    container_name: celery-worker
    env_file: 
      - .env
    entrypoint: scripts/entrypoint.sh
    command: celery-worker
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/src/blanball
    networks:
      - app-network
    depends_on:
      db:
        condition: service_started
      api:
        condition: service_started

  celery-beat:
    container_name: celery-beat
    env_file: 
      - .env
    entrypoint: scripts/entrypoint.sh
    command: celery-beat
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/src/blanball
    networks:
      - app-network
    depends_on:
      db:
        condition: service_started
      api:
        condition: service_started

  ftp-server:
    container_name: ftp-server
    env_file: 
      - .env
    image: garethflowers/ftp-server
    ports:
      - 21:21/tcp
    volumes:
      - ftp-server-data:/home/user
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  ftp-server-data:
