version: "3.7"

services: 
  api:
    container_name: api
    build: .
    command: bash start.sh
    restart: always
    volumes:
      - .:/usr/src/blanball
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    links: 
      - db
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 3s
      retries: 5
    
  db:
    container_name: db
    ports:
      - 3307:3306
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: 'blanball'
      MYSQL_PASSWORD: 'Djoncarton1921_'
      MYSQL_ROOT_HOST: '%'  
      MYSQL_ROOT_PASSWORD: 'Djoncarton1921_'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 40s
      retries: 20

volumes:
  db:
    driver: local





    