version: '3.8'

x-api-common: &api-common
    env_file:
        - .env
    entrypoint: scripts/entrypoint.sh
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/usr/src/blanball
    networks:
        - blaball-network
    depends_on:
        db:
            condition: service_healthy
        redis:
            condition: service_healthy
    links:
        - redis

services:
    db:
        container_name: db
        env_file:
            - .env
        image: postgis/postgis:latest
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        networks:
            - blaball-network
        ports:
            - 5432:5432
        healthcheck:
            test: pg_isready -U postgres -d postgres
            timeout: 5s
            retries: 20

    redis:
        container_name: redis
        env_file:
            - .env
        image: redis:7.0.4-alpine
        volumes:
            - redis-data:/usr/src/blanball/storage/redis/data
        networks:
            - blaball-network
        healthcheck:
            test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
            timeout: 5s
            retries: 20

    api:
        <<: *api-common
        container_name: api
        command: api
        ports:
            - 8000:8000

    daphne:
        <<: *api-common
        container_name: daphne
        command: daphne
        ports:
            - 10000:10000

    celery-worker:
        <<: *api-common
        container_name: celery-worker
        command: celery-worker
        user: deploy

    celery-beat:
        <<: *api-common
        container_name: celery-beat
        command: celery-beat
        user: deploy

    minio:
        container_name: minio
        env_file:
            - .env
        image: minio/minio
        volumes:
            - minio-data:/minio-data
        command: 'minio server /minio-data --console-address ":9001"'
        ports:
            - 9000:9000
            - 9001:9001
        healthcheck:
            test:
                ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 30s
            timeout: 20s
            retries: 3
        networks:
            - blaball-network
    pgadmin:
        container_name: pgadmin
        env_file:
            - .env
        image: dpage/pgadmin4:latest
        restart: always
        volumes:
            - pgadmin-data:/usr/src/blanball/storage/pgadmin/data
        networks:
            - blaball-network
        ports:
            - 49280:49299

    kafka:
        container_name: kafka
        env_file:
            - .env
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
            - 9093:9093
        restart: always
        volumes:
            - kafka-data:/usr/src/blanball/storage/kafka/data
        networks:
            - blaball-network

    zookeeper:
        container_name: zookeeper
        env_file:
            - .env
        image: zookeeper:latest
        ports:
            - 2181:2181
        restart: always
        volumes:
            - zookeeper-data:/usr/src/blanball/storage/zookeeper/data \
            - zookeeper-logs-data:/usr/src/blanball/storage/zookeeper-logs/data \
        networks:
            - blaball-network

networks:
    blaball-network:
        name: blaball-network

volumes:
    redis-data:
    minio-data:
    pgadmin-data:
    kafka-data:
    zookeeper-data:
    zookeeper-logs-data:
