version: "3.7"

services: 
  web:
    container_name: django_web
    build: .
    command: bash start.sh
    volumes:
      - .:/usr/src/blanball
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db
  redis:
    container_name: redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    ports:
      - 3306:3306
    container_name: mysql_db
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'blanball'
      MYSQL_PASSWORD: 'Djoncarton1921_'
      MYSQL_ROOT_HOST: '%'  
      MYSQL_ROOT_PASSWORD: 'Djoncarton1921_'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10



# version: "3.7"

# services: 
#   db:
#     ports:
#       - 3306:3306
#     container_name: db
#     image: mysql:8
#     cap_add:
#       - SYS_NICE
#     restart: always
#     volumes:
#       - db:/var/lib/mysql
#     environment:
#       MYSQL_DATABASE: 'blanball'
#       MYSQL_PASSWORD: 'Djoncarton1921_'
#       MYSQL_ROOT_HOST: '%'  
#       MYSQL_ROOT_PASSWORD: 'Djoncarton1921_'
#     healthcheck:
#       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#       timeout: 40s
#       retries: 20

#   api:
#     container_name: api
#     build: .
#     command: bash start.sh
#     restart: always
#     volumes:
#       - .:/usr/src/blanball
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#         # condition: service_healthy
#     links: 
#       - db

# volumes:
#   db:
#     driver: local