# Generated by Django 4.1.1 on 2022-10-19 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='black_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
