# Generated by Django 4.1.1 on 2022-11-03 17:37

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
