# Generated by Django 4.1.1 on 2022-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_contact_number_alter_event_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.JSONField(),
        ),
    ]
