# Generated by Django 4.1.1 on 2022-11-12 12:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_contact_number_alter_event_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="place",
            field=django.contrib.gis.db.models.fields.PointField(srid=3875),
        ),
    ]
