# Generated by Django 4.1.1 on 2022-11-12 15:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_event_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
