# Generated by Django 4.1.1 on 2023-01-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_coordinates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-id"],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="invitetoevent",
            options={
                "ordering": ["-id"],
                "verbose_name": "invite to event",
                "verbose_name_plural": "invites to event",
            },
        ),
        migrations.AlterModelOptions(
            name="requesttoparticipation",
            options={
                "ordering": ["-id"],
                "verbose_name": "request to participation",
                "verbose_name_plural": "requests to participation",
            },
        ),
    ]
