# Generated by Django 4.1.1 on 2023-02-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_alter_event_options_alter_invitetoevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="forms",
            field=models.CharField(
                choices=[
                    ("Shirt-Front", "Shirt Front"),
                    ("T-Shirt", "T Shirt"),
                    ("Any", "Any"),
                ],
                max_length=500,
            ),
        ),
    ]
