# Generated by Django 4.1.1 on 2023-01-16 14:55

from django.db import migrations


def set_forms(apps, schema_editor):
    """
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        event.forms = {
            "first_team": {"type": "Shirt-Front", "color": "#000"},
            "second": {"type": "Shirt-Front", "color": "#000"},
        }
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_alter_event_forms"),
    ]

    operations = [
        migrations.RunPython(set_forms, migrations.RunPython.noop),
    ]
