# Generated by Django 4.1.1 on 2023-02-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_convert_forms_to_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="forms",
            field=models.JSONField(null=True),
        ),
    ]
