# Generated by Django 4.1.1 on 2023-02-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_event_forms"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
