# Generated by Django 4.1.1 on 2023-02-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="price_description",
            field=models.CharField(max_length=265, null=True),
        ),
    ]
