# Generated by Django 4.1.1 on 2023-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_event_price_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
