# Generated by Django 4.1.1 on 2022-12-22 16:18

import authentication.models
import bugs.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to=bugs.models.bug_image_name,
                        validators=[authentication.models.validate_image],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Closed", "Closed"), ("Open", "Open")],
                        default="Open",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
