# Generated by Django 4.1.1 on 2022-12-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="type",
            field=models.CharField(
                choices=[
                    ("Closed", "Closed"),
                    ("Consideration", "Consideration"),
                    ("Open", "Open"),
                ],
                default="Open",
                max_length=15,
            ),
        ),
    ]
