# Generated by Django 4.1.1 on 2022-12-26 17:39

import authentication.models.profile_model
import bugs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0002_alter_bug_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to=bugs.models.bug_image_name,
                        validators=[authentication.models.profile_model.validate_image],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="bug",
            name="image",
        ),
        migrations.AddField(
            model_name="bug",
            name="images",
            field=models.ManyToManyField(blank=True, to="bugs.bugimage"),
        ),
    ]
