# Generated by Django 4.1.1 on 2023-01-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0003_bugimage_remove_bug_image_bug_images"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bug",
            options={"verbose_name": "bug", "verbose_name_plural": "bugs"},
        ),
        migrations.AlterModelOptions(
            name="bugimage",
            options={"verbose_name": "bug_image", "verbose_name_plural": "bug_images"},
        ),
        migrations.AlterModelTable(
            name="bug",
            table="bug",
        ),
        migrations.AlterModelTable(
            name="bugimage",
            table="bug_image",
        ),
    ]
