# Generated by Django 4.1.1 on 2023-01-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bugs", "0004_alter_bug_options_alter_bugimage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bug",
            options={
                "ordering": ["-id"],
                "verbose_name": "bug",
                "verbose_name_plural": "bugs",
            },
        ),
    ]
