# Generated by Django 4.1.1 on 2023-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hints", "0002_remove_hint_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
