# Generated by Django 4.0.4 on 2022-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='get_planned_events',
            field=models.CharField(default='1m', max_length=10),
        ),
    ]
