# Generated by Django 4.0.4 on 2022-09-10 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='life_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 10, 14, 58, 6, 866367, tzinfo=utc), null=True),
        ),
    ]
