# Generated by Django 4.1.1 on 2022-10-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'Gk'), ('LB', 'Lb'), ('RB', 'Rb'), ('CB', 'Cb'), ('LWB', 'Lwb'), ('RWB', 'Rwb'), ('CDM', 'Cdm'), ('CM', 'Cm'), ('CAM', 'Cam'), ('RM', 'Rm'), ('LM', 'Lm'), ('RW', 'Rw'), ('LW', 'Lw'), ('RF', 'Rf'), ('CF', 'Cf'), ('LF', 'Lf'), ('ST', 'St')], max_length=255, null=True),
        ),
    ]
