# Generated by Django 4.0.4 on 2022-08-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woomen', 'Woomen'), ('All', 'All')], max_length=10),
        ),
    ]
