# Generated by Django 4.1.1 on 2022-10-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Wooman', 'Wooman')], max_length=10),
        ),
    ]
