# Generated by Django 4.1.1 on 2022-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'code', 'verbose_name_plural': 'codes'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Wooman', 'Wooman')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
        migrations.DeleteModel(
            name='ActiveUser',
        ),
    ]
