# Generated by Django 4.1.1 on 2022-09-26 12:58

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='srv/sftp/'),
        ),
    ]
