# Generated by Django 4.1.1 on 2022-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="working_leg",
            field=models.CharField(
                choices=[("Left", "Left"), ("Right", "Right")],
                max_length=255,
                null=True,
            ),
        ),
    ]
