# Generated by Django 4.1.1 on 2022-11-17 07:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_profile_working_leg"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="profile",
            name="place",
            field=models.JSONField(null=True),
        ),
    ]
