# Generated by Django 4.1.1 on 2022-11-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_profile_coordinates_profile_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="place",
            field=models.JSONField(),
        ),
    ]
