# Generated by Django 4.1.1 on 2022-11-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_profile_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="place",
            field=models.JSONField(null=True),
        ),
    ]
