# Generated by Django 4.1.1 on 2022-11-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Man", "Man"), ("Woman", "Woman")], max_length=10, null=True
            ),
        ),
    ]
