# Generated by Django 4.1.1 on 2023-01-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_profile_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-id"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
