# Generated by Django 4.1.1 on 2023-05-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hints", "0001_initial"),
        (
            "authentication",
            "0014_alter_profile_about_me_alter_profile_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="checked_hints",
            field=models.ManyToManyField(
                blank=True, related_name="checked_hints", to="hints.hint"
            ),
        ),
    ]
