# Generated by Django 4.1.1 on 2023-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hints", "0002_remove_hint_page"),
        ("authentication", "0015_user_checked_hints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="checked_hints",
            field=models.ManyToManyField(blank=True, to="hints.hint"),
        ),
    ]
