# Generated by Django 4.1.1 on 2023-06-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_alter_user_checked_hints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="place",
            field=models.JSONField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
