# Generated by Django 4.1.1 on 2023-01-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={"verbose_name": "api key", "verbose_name_plural": "api keys"},
        ),
        migrations.AddField(
            model_name="apikey",
            name="expire_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="value",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name="apikey",
            table="api_key",
        ),
    ]
