# Generated by Django 4.1.1 on 2023-01-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0002_alter_apikey_options_apikey_expire_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "ordering": ["-id"],
                "verbose_name": "api key",
                "verbose_name_plural": "api keys",
            },
        ),
    ]
