# Generated by Django 4.1.1 on 2023-01-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0003_alter_apikey_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="name",
            field=models.CharField(max_length=55, null=True, unique=True),
        ),
    ]
