# Generated by Django 4.1.1 on 2023-01-16 14:55

from django.db import migrations


def set_name(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    ApiKey = apps.get_model('api_keys', 'ApiKey')
    for api_key in ApiKey.objects.all():
        api_key.name = api_key.id
        api_key.save()

class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0004_apikey_name"),
    ]

    operations = [
        migrations.RunPython(set_name, migrations.RunPython.noop),
    ]