# Generated by Django 4.1.1 on 2023-01-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0005_auto_20230116_1455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
