# Generated by Django 4.1.1 on 2023-06-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_keys", "0006_alter_apikey_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="expire_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="value",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
