# Generated by Django 4.0.4 on 2022-08-03 10:43

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('small_disc', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Man', 'Man'), ('Woomen', 'Woomen')], max_length=100)),
                ('date_and_time', models.DateTimeField()),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('need_ball', models.BooleanField()),
                ('amount_members', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(choices=[('Football', 'Football'), ('Futsal', 'Futsal')], max_length=100)),
                ('price', models.PositiveSmallIntegerField()),
                ('price_description', models.CharField(max_length=500)),
                ('need_form', models.BooleanField()),
                ('team1_form_color', models.CharField(blank=True, max_length=50, null=True)),
                ('team2_form_color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
