on: [push,workflow_dispatch]

env:
  PROXY_REGISTRY: ${{ secrets.DOCKER_PROXY_REGISTRY }}
  PROXY_LATEST_IMAGE: ${{ secrets.DOCKER_PROXY_REGISTRY }}:latest
  PROXY_COMMIT_IMAGE: ${{ secrets.DOCKER_PROXY_REGISTRY }}:${{ github.sha }}

jobs:
  deploy-proxy:
  steps:
  - uses: actions/checkout@master
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v2
    with:
      registry: ${{ env.PROXY_REGISTRY }}
      username: ${{ secrets.REGISTRY_USERNAME }}
      password: ${{ secrets.REGISTRY_PASSWORD }}
  - name: Build image (PROXY)
    working-directory: .
    run: |
      docker build -f ${{ env.PROXY_DOCKERFILE_PATH }} -t api --cache-from ${{ env.PROXY_LATEST_IMAGE }} -t ${{ env.PROXY_COMMIT_IMAGE }} .
  - name: Tag latest image (PROXY)
    run: |
      docker tag ${{ env.PROXY_COMMIT_IMAGE }} ${{ env.PROXY_LATEST_IMAGE }}
  - name: Push images (PROXY)
    run: |
      docker push ${{ env.PROXY_COMMIT_IMAGE }}
      docker push ${{ env.PROXY_LATEST_IMAGE }