name: change_version

on:
  push:

jobs:
  build_proxy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update package.json version
      uses: jossef/action-set-json-field@v2.1
      with:
        file: project/config/config.json
        field: version
        value: 0
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "auto update version"
        git tag ${{ steps.semantic_release_info.outputs.git_tag }}
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ github.token }}