name: Deploy
on:
  push:
    branches: [ "dev_test","main_test" ]
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main_test')]
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev_test')]

jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      if [ "${isDevelop}" == "true" ]; then
        LATEST_IMAGE: ${{ secrets.DOCKER_REGISTRY }}:latest
        COMMIT_IMAGE: ${{ secrets.DOCKER_REGISTRY }}:${{ github.sha }}
      fi
      DOCKERFILE_PATH: Dockerfile
    steps:
    - uses: actions/checkout@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull latest image
      run: |
        docker pull ${LATEST_IMAGE} --ignore-pull-failures || true
    - name: Build image
      working-directory: .
      run: |
        docker build -f ${DOCKERFILE_PATH} --cache-from ${LATEST_IMAGE} -t ${COMMIT_IMAGE} .
    - name: Tag latest image
      run: |
        docker tag ${COMMIT_IMAGE} ${LATEST_IMAGE}
    - name: Push images
      run: |
        docker push ${COMMIT_IMAGE}
        docker push ${LATEST_IMAGE}
        
    - name: Trigger deploy in portainer
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
