name: Deploy
on:
  push:
    branches: [ "dev_test","main_test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_PATH: Dockerfile
      with:
        cond: ${{ github.ref == 'refs/heads/dev_test' }}
        if_true:
          LATEST_IMAGE: ${{ secrets.DOCKER_REGISTRY_TEST }}:latest
          COMMIT_IMAGE: ${{ secrets.DOCKER_REGISTRY_TEST }}:${{ github.sha }}
        if_false:
          LATEST_IMAGE: ${{ secrets.DOCKER_REGISTRY_PROD }}:latest
          COMMIT_IMAGE: ${{ secrets.DOCKER_REGISTRY_PROD }}:${{ github.sha }}
    steps:
    - uses: actions/checkout@master

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        if: ${{ github.ref == 'refs/heads/dev_test' }}
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull latest image
      run: |
        docker pull ${LATEST_IMAGE} --ignore-pull-failures || true
    - name: Build image
      working-directory: .
      run: |
        docker build -f ${DOCKERFILE_PATH} --cache-from ${LATEST_IMAGE} -t ${COMMIT_IMAGE} .
    - name: Tag latest image
      run: |
        docker tag ${COMMIT_IMAGE} ${LATEST_IMAGE}
    - name: Push images
      run: |
        docker push ${COMMIT_IMAGE}
        docker push ${LATEST_IMAGE}
        
    - name: Trigger deploy in portainer in dev branch
      if: ${{ github.ref == 'refs/heads/dev_test' }}
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_TEST }}

    - name: Trigger deploy in portainer in dev branch
      if: ${{ github.ref == 'refs/heads/main_test' }}
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_PROD }}
