name: Deploy
on:
  push:
    branches: [ "dev_test" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env vars (dev)
      if: endsWith(github.ref, '/dev_test')
      run: |
        echo "AZURE_FUNCTIONAPP_NAME=Dockerfile"
        echo "PUBLISH_PROFILE_VAR_NAME=DOCKER_REGISTRY:latest"
        echo "COMMIT_IMAGE=DOCKER_REGISTRY:${{ github.sha }}"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull latest image
      run: |
        docker pull ${LATEST_IMAGE} --ignore-pull-failures || true
    - name: Build image
      working-directory: .
      run: |
        docker build -f ${ AZURE_FUNCTIONAPP_NAME } --cache-from  ${{ secrets[env.PUBLISH_PROFILE_VAR_NAME] }}-t {{ secrets[env.COMMIT_IMAGE] }} .
    - name: Tag latest image
      run: |
        docker tag ${COMMIT_IMAGE} ${LATEST_IMAGE}
    - name: Push images
      run: |
        docker push ${COMMIT_IMAGE}
        docker push ${LATEST_IMAGE}
        
    - name: Trigger deploy in portainer
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}


      # if: ${{ github.ref == 'refs/dev_test' }}