name: Deploy
on:
  push:
    branches: [ "dev_test" ]
if: ${{ github.ref == 'refs/dev_test' }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env vars (dev)
      if: endsWith(github.ref, '/dev')
      run: |
        echo "DOCKERFILE_PATH=Dockerfile" >> $GITHUB_ENV
        echo "LATEST_IMAGE=${{ secrets.DOCKER_REGISTRY }}:latest" >> $GITHUB_ENV
        echo "COMMIT_IMAGE=${{ secrets.DOCKER_REGISTRY }}:${{ github.sha }}" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull latest image
      run: |
        docker pull ${LATEST_IMAGE} --ignore-pull-failures || true
    - name: Build image
      working-directory: .
      run: |
        docker build -f ${DOCKERFILE_PATH} --cache-from ${LATEST_IMAGE} -t ${COMMIT_IMAGE} .
    - name: Tag latest image
      run: |
        docker tag ${COMMIT_IMAGE} ${LATEST_IMAGE}
    - name: Push images
      run: |
        docker push ${COMMIT_IMAGE}
        docker push ${LATEST_IMAGE}
        
    - name: Trigger deploy in portainer
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
