name: Deploy
on:
  push:
    branches: [ "dev_test","master_test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_PATH: Dockerfile
    steps:
    - uses: actions/checkout@master

    - name: Set env vars (dev)
      if: github.ref == 'refs/heads/dev_test'
      run: |
        echo "LATEST_IMAGE=${{ secrets.DOCKER_REGISTRY_TEST }}:latest" >> $GITHUB_ENV
        echo "COMMIT_IMAGE=${{ secrets.DOCKER_REGISTRY_TEST }}:${{ github.sha }}" >> $GITHUB_ENV
    - name: Set env vars (prod)
      if: github.ref == 'refs/heads/master_test'
      run: |
        echo "LATEST_IMAGE=${{ secrets.DOCKER_REGISTRY_PROD }}:latest" >> $GITHUB_ENV
        echo "COMMIT_IMAGE=${{ secrets.DOCKER_REGISTRY_PROD }}:${{ github.sha }}" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull latest image
      run: |
        docker pull ${LATEST_IMAGE} --ignore-pull-failures || true
    - name: Build image
      working-directory: .
      run: |
        docker build -f ${DOCKERFILE_PATH} --cache-from ${LATEST_IMAGE} -t ${COMMIT_IMAGE} .
    - name: Tag latest image
      run: |
        docker tag ${COMMIT_IMAGE} ${LATEST_IMAGE}
    - name: Push images
      run: |
        docker push ${COMMIT_IMAGE}
        docker push ${LATEST_IMAGE}

    - name: Trigger deploy in portainer (dev)
      if: github.ref == 'refs/heads/dev_test'
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_TEST }}
      
    - name: Trigger deploy in portainer (prod)
      if: github.ref == 'refs/heads/main_test'
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_PROD }}
